# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Downloads/miniRV_basic_minisys/miniRV_basic/src/rtl/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/miniRV_basic_minisys/miniRV_basic/src/rtl/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Downloads/miniRV_basic_minisys/miniRV_basic/src/rtl/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/miniRV_basic_minisys/miniRV_basic/src/rtl/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
